version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather-frontend
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend
    

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather-backend
    ports:
      - "8000:8000"
    restart: always
